name: CD

# Run when tags are pushed
on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.1.0
    - name: Install dependencies
      run: yarn --network-concurrency 1
    - run: yarn build
      env:
        REACT_APP_FB_KEY: ${{ secrets.REACT_APP_FB_KEY }}
        REACT_APP_INFURA_KEY: ${{ secrets.REACT_APP_INFURA_KEY }}
        REACT_APP_SENTRY_DSN: ${{ secrets.REACT_APP_SENTRY_DSN }}
        CI: false
    - uses: netlify/actions/cli@master
      with:
        args: deploy --dir=./build
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
